# Site settings
title: Divisio
tagline: Market
description: > # this means to ignore newlines until "baseurl:"
The place to invest in alternative assets
baseurl: "/web" # the subpath of your site, e.g. /blog
url: "https://divisiomarket.github.io" # the base hostname & protocol for your site

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"
